version: '3.8'

services:
  backend:
    image: ghcr.io/phuuthanh-dev/pet-love-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: ghcr.io/phuuthanh-dev/pet-love-frontend:latest
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always
