export const dogBreeds = [
  "-- Vui lòng chọn giống chó --",
  'Pembroke',
  "Domestic Dog",
  "Affenpinscher",
  "Afghan Hound",
  "Akita",
  "Alaskan Malamute",
  "American Staffordshire terrier",
  "American Water Spaniel",
  "Australian cattle dog",
  "Australian shepherd",
  "Australian terrier",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bedlington Terrier",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Black And Tan Coonhound",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier Des Flandres",
  "Boxer",
  "Briard",
  "Brittany",
  "Brussels Griffon",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Canaan Dog",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested",
  "Chinese Shar-pei",
  "Chow Chow",
  "Clumber Spaniel",
  "Cocker Spaniel",
  "Collie",
  "Curly-coated Retriever",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "English Cocker Spaniel",
  "English Setter",
  "English Springer Spaniel",
  "English Toy Spaniel",
  "Eskimo Dog",
  "Finnish Spitz",
  "Flat-coated Retriever",
  "Fox Terrier",
  "Foxhound",
  "French Bulldog",
  "German Shepherd",
  "German Shorthaired pointer",
  "German Wirehaired pointer",
  "Golden Retriever",
  "Gordon Setter",
  "Great Dane",
  "Greyhound",
  "Irish Setter",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Jack Russell Terrier",
  "Japanese Spaniel",
  "Keeshond",
  "Kerry Blue Terrier",
  "Komondor",
  "Kuvasz",
  "Labrador Retriever",
  "Lakeland Terrier",
  "Lhasa Apso",
  "Maltese",
  "Manchester Terrier",
  "Mastiff",
  "Mexican Hairless",
  "Newfoundland",
  "Norwegian Elkhound",
  "Norwich Terrier",
  "Otterhound",
  "Papillon",
  "Pekingese",
  "Pointer",
  "Pomeranian",
  "Poodle",
  "Pug",
  "Puli",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saint Bernard",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Schnauzer",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Shetland Sheepdog",
  "Shih Tzu",
  "Siberian Husky",
  "Silky Terrier",
  "Skye Terrier",
  "Staffordshire Bull Terrier",
  "Soft-coated Wheaten Terrier",
  "Sussex Spaniel",
  "Spitz",
  "Tibetan Terrier",
  "Vizsla",
  "Weimaraner",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "Yorkshire Terrier",
];
